Repository OCA/l10n-usa, pull requests merged in 2025-03, with the labels that each got.

#143 [18.0][MIG] l10n_us_account_routing: Migration to 18.0
  l10n_us_account_routing/README.rst
  l10n_us_account_routing/__init__.py
  l10n_us_account_routing/__manifest__.py
  l10n_us_account_routing/i18n/l10n_us_account_routing.pot
  l10n_us_account_routing/models/__init__.py
  l10n_us_account_routing/models/res_bank.py
  l10n_us_account_routing/pyproject.toml
  l10n_us_account_routing/readme/CONTRIBUTORS.md
  l10n_us_account_routing/readme/DESCRIPTION.md
  l10n_us_account_routing/static/description/icon.png
  l10n_us_account_routing/static/description/index.html
  l10n_us_account_routing/tests/__init__.py
  l10n_us_account_routing/tests/test_routing_number_bank.py
  l10n_us_account_routing/views/res_bank.xml
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#126 [14.0] ocabot update dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .oca_hooks.cfg
  .pre-commit-config.yaml
  .ruff.toml
  .travis.yml
  README.md
  account_banking_ach_base/__manifest__.py
  account_banking_ach_base/models/res_bank.py
  account_banking_ach_base/static/description/index.html
  account_banking_ach_discount/__manifest__.py
  account_banking_ach_discount/models/account_payment_order.py
  account_banking_ach_discount/wizard/account_payment_register.py
  l10n_us_gaap/data/account_chart_template_data.xml
  l10n_us_gaap/data/account_us_gaap_data.xml
  l10n_us_partner_legal_number/__manifest__.py
  setup/account_banking_ach_discount/odoo/addons/account_banking_ach_discount
  setup/account_banking_ach_discount/setup.py
Labels: bot is merging ⏳

#89 [14.0][ADD] partner_usps_address_validation
  partner_usps_address_validation/README.rst
  partner_usps_address_validation/__init__.py
  partner_usps_address_validation/__manifest__.py
  partner_usps_address_validation/models/__init__.py
  partner_usps_address_validation/models/res_partner.py
  partner_usps_address_validation/models/usps_credential_configuration.py
  partner_usps_address_validation/readme/CONFIGURATION.rst
  partner_usps_address_validation/readme/CONTRIBUTORS.rst
  partner_usps_address_validation/readme/CREDITS.rst
  partner_usps_address_validation/readme/DESCRIPTION.rst
  partner_usps_address_validation/requirements.txt
  partner_usps_address_validation/security/ir.model.access.csv
  partner_usps_address_validation/static/description/icon.png
  partner_usps_address_validation/static/description/index.html
  partner_usps_address_validation/views/config.xml
  partner_usps_address_validation/views/res_partner.xml
  partner_usps_address_validation/wizard/__init__.py
  partner_usps_address_validation/wizard/usps_address_validation.py
  partner_usps_address_validation/wizard/usps_address_validation.xml
  requirements.txt
  setup/partner_usps_address_validation/odoo/addons/partner_usps_address_validation
  setup/partner_usps_address_validation/setup.py
Labels: bot is merging ⏳, stale

#102 [16.0][mig] partner_usps_address_validation
  partner_usps_address_validation/README.rst
  partner_usps_address_validation/__init__.py
  partner_usps_address_validation/__manifest__.py
  partner_usps_address_validation/models/__init__.py
  partner_usps_address_validation/models/res_partner.py
  partner_usps_address_validation/models/usps_credential_configuration.py
  partner_usps_address_validation/readme/CONFIGURATION.rst
  partner_usps_address_validation/readme/CONTRIBUTORS.rst
  partner_usps_address_validation/readme/CREDITS.rst
  partner_usps_address_validation/readme/DESCRIPTION.rst
  partner_usps_address_validation/requirements.txt
  partner_usps_address_validation/security/ir.model.access.csv
  partner_usps_address_validation/static/description/icon.png
  partner_usps_address_validation/static/description/index.html
  partner_usps_address_validation/views/config.xml
  partner_usps_address_validation/views/res_partner.xml
  partner_usps_address_validation/wizard/__init__.py
  partner_usps_address_validation/wizard/usps_address_validation.py
  partner_usps_address_validation/wizard/usps_address_validation.xml
  requirements.txt
  setup/partner_usps_address_validation/odoo/addons/partner_usps_address_validation
  setup/partner_usps_address_validation/setup.py
Labels: bot is merging ⏳, stale

#137 [17.0][MIG] account_banking_ach_base
  account_banking_ach_base/README.rst
  account_banking_ach_base/__init__.py
  account_banking_ach_base/__manifest__.py
  account_banking_ach_base/i18n/account_banking_ach_base.pot
  account_banking_ach_base/models/__init__.py
  account_banking_ach_base/models/account_banking_mandate.py
  account_banking_ach_base/models/account_move.py
  account_banking_ach_base/models/account_payment_method.py
  account_banking_ach_base/models/account_payment_order.py
  account_banking_ach_base/models/res_bank.py
  account_banking_ach_base/models/res_company.py
  account_banking_ach_base/pyproject.toml
  account_banking_ach_base/readme/CONTRIBUTORS.md
  account_banking_ach_base/readme/DESCRIPTION.md
  account_banking_ach_base/readme/USAGE.md
  account_banking_ach_base/static/description/icon.png
  account_banking_ach_base/static/description/index.html
  account_banking_ach_base/views/account_banking_mandate.xml
  account_banking_ach_base/views/account_move.xml
  account_banking_ach_base/views/res_bank.xml
  account_banking_ach_base/views/res_company.xml
  requirements.txt
Labels: bot is merging ⏳

#133 [17.0][MIG] l10n_us_gaap_mis_report
  l10n_us_gaap_mis_report/README.rst
  l10n_us_gaap_mis_report/__init__.py
  l10n_us_gaap_mis_report/__manifest__.py
  l10n_us_gaap_mis_report/data/mis_report_balance_sheet.xml
  l10n_us_gaap_mis_report/data/mis_report_income_statement.xml
  l10n_us_gaap_mis_report/data/mis_report_styles.xml
  l10n_us_gaap_mis_report/docs/l10n_us_gaap_balance_sheet.ods
  l10n_us_gaap_mis_report/docs/l10n_us_gaap_income_statement.ods
  l10n_us_gaap_mis_report/i18n/es.po
  l10n_us_gaap_mis_report/i18n/l10n_us_gaap_mis_report.pot
  l10n_us_gaap_mis_report/pyproject.toml
  l10n_us_gaap_mis_report/readme/CONFIGURE.md
  l10n_us_gaap_mis_report/readme/CONTRIBUTORS.md
  l10n_us_gaap_mis_report/readme/DESCRIPTION.md
  l10n_us_gaap_mis_report/readme/INSTALL.md
  l10n_us_gaap_mis_report/static/description/icon.png
  l10n_us_gaap_mis_report/static/description/index.html
Labels: bot is merging ⏳
